name: "datasette-test-application"
services: 
  - dockerfilePath: Dockerfile
    github:
      branch: main
      repo: laneysmith/datasette
# databases:
#   - name: test
#     engine: PG
#     version: 12
#     production: false
#     size: db-s-dev-database
#     num_nodes: 1
