name: "datasette-test-application"
services: 
  - dockerfilePath: Dockerfile
    github:
      branch: main
      repo: laneysmith/datasette
#     git:
#       branch: main
#       repo_clone_url: https://github.com/laneysmith/datasette
    # http_port: 7379
    routes: 
      - path: /
databases:
  - name: "datasette-dev-db"
    version: 12
    size: "db-s-dev-database"
    num_nodes: 1
    engine: "PG"
